name: Docker Build Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repozytorium
      - name: Checkout code
        uses: actions/checkout@v3

      # Logowanie do Docker Hub (opcjonalnie, jeśli używasz zdalnego rejestru)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Budowanie obrazu Dockerowego
      - name: Build Docker Image
        run: |
          docker build -t myapp:latest .

      # Opcjonalnie: Sprawdzenie działania obrazu
      - name: Test Docker Image
        run: |
          docker run --rm myapp:latest echo "Docker Image Built Successfully"
